services:
  notification-service:
    build:
      context: . 
    container_name: notification-container
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      # GET RABBIT CONFIG FROM .ENV
      SPRING_RABBITMQ_HOST: ${RABBIT_HOST} 
      SPRING_RABBITMQ_PORT: ${RABBIT_PORT} 
      SPRING_RABBITMQ_USERNAME: ${RABBIT_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASSWORD}
      SPRING_RABBITMQ_VHOST: ${RABBIT_VHOST}
      
      # GET MAIL CONFIG FROM ENV
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      

      SERVER_PORT: ${SERVER_PORT}
      RABBIT_QUEUE_NAME: ${EMAIL_QUEUE_NAME}
      NOTIFICATION_EXCHANGE: ${NOTIFICATION_EXCHANGE}
      EMAIL_ROUTING: ${EMAIL_ROUTING}
      
      JAVA_OPTS: "-Xmx512m -Xms256m"
      
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge